"use strict";
const crypto=require("node:crypto");
const {AppError}=require("./mvp-service");
const {hashPassword,sessionTokenHash}=require("./admin-auth");
const PROPERTY_ID=/^[a-z][a-z0-9_]{2,47}$/;
const ALLOWED_ATTACHMENTS=new Map([[".csv","text/csv"],[".xls","application/vnd.ms-excel"],[".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],[".ics","text/calendar"],[".ical","text/calendar"],[".png","image/png"],[".jpg","image/jpeg"],[".jpeg","image/jpeg"],[".pdf","application/pdf"]]);
function text(value,max=500){const v=String(value||"").trim();if(v.length>max)throw new AppError(400,"TEXT_TOO_LONG","欄位內容過長");return v;}
function integer(value,min=0){const n=Number(value);if(!Number.isInteger(n)||n<min)throw new AppError(400,"INVALID_NUMBER","數值格式錯誤");return n;}
function cleanInput(input={}){const rooms=(input.rooms||[]).map((x,i)=>({key:text(x.key||`room_${i+1}`,40),name:text(x.name,80),type:text(x.type,40),capacity:integer(x.capacity,1),basePrice:integer(x.basePrice),weekdayPrice:integer(x.weekdayPrice),fridayPrice:integer(x.fridayPrice),saturdayPrice:integer(x.saturdayPrice),features:text(x.features,500),enabled:x.enabled!==false}));const keys=new Set(rooms.map(x=>x.key));if(keys.size!==rooms.length)throw new AppError(400,"DUPLICATE_ROOM_KEY","房型識別重複");const bundles=(input.bundles||[]).map((x,i)=>{const members=[...new Set((x.memberRoomKeys||[]).map(v=>text(v,40)))];if(!members.length||members.some(k=>!keys.has(k)))throw new AppError(400,"INVALID_BUNDLE_MEMBER","包棟成員房型錯誤");return{key:text(x.key||`bundle_${i+1}`,40),name:text(x.name,80),memberRoomKeys:members,capacity:integer(x.capacity,1),basePrice:integer(x.basePrice),weekdayPrice:integer(x.weekdayPrice),fridayPrice:integer(x.fridayPrice),saturdayPrice:integer(x.saturdayPrice),enabled:x.enabled!==false};});const knowledge=(input.knowledge||[]).map((x,i)=>{const status=["fixed","unavailable","human_handoff","undecided"].includes(x.status)?x.status:"undecided";const answer=text(x.answer,1000);if(status==="fixed"&&!answer)throw new AppError(400,"MISSING_KNOWLEDGE_ANSWER","固定答案不可空白");return{key:text(x.key||`faq_${i+1}`,80),label:text(x.label,120),status,answer};});return{propertyName:text(input.propertyName,100),contactName:text(input.contactName,80),phone:text(input.phone,40),email:text(input.email,160),address:text(input.address,300),description:text(input.description,1000),checkInTime:text(input.checkInTime,5),checkOutTime:text(input.checkOutTime,5),line:{hasOfficialAccount:Boolean(input.line&&input.line.hasOfficialAccount),channelId:text(input.line&&input.line.channelId,80),contactLink:text(input.line&&input.line.contactLink,500)},availabilitySource:{type:["none","csv","excel","ical","system","attachment"].includes(input.availabilitySource&&input.availabilitySource.type)?input.availabilitySource.type:"none",systemName:text(input.availabilitySource&&input.availabilitySource.systemName,100)},propertyIdSuggestion:text(input.propertyIdSuggestion,48),rooms,bundles,knowledge};}
function completeness(app){const required=["propertyName","contactName","phone","email","address","checkInTime","checkOutTime"],missing=required.filter(k=>!app[k]);if(!app.rooms||!app.rooms.length)missing.push("rooms");return{percent:Math.round((required.length+1-missing.length)/(required.length+1)*100),missing,contradictions:[]};}
function createOnboardingService(provider){
  if(!provider)return null;
  async function authorized(id,token){if(!token||!provider.verifyOnboardingToken(id,sessionTokenHash(token)))throw new AppError(401,"INVALID_DRAFT_TOKEN","草稿驗證失敗");}
  return{
    createDraft(){const applicationId=crypto.randomUUID(),draftToken=crypto.randomBytes(32).toString("base64url");provider.createOnboarding(applicationId,sessionTokenHash(draftToken));return{applicationId,draftToken,status:"draft"};},
    async getDraft(id,token){await authorized(id,token);const item=provider.getOnboarding(id);if(!item)throw new AppError(404,"APPLICATION_NOT_FOUND","找不到申請案件");return item;},
    async saveDraft(id,token,input){await authorized(id,token);return provider.saveOnboarding(id,cleanInput(input));},
    async preview(id,token){const item=await this.getDraft(id,token);return{...item,completeness:completeness(item)};},
    async addAttachment(id,token,file){await authorized(id,token);const ext=require("node:path").extname(file.fileName).toLowerCase(),expected=ALLOWED_ATTACHMENTS.get(ext);if(!expected||expected!==file.contentType)throw new AppError(415,"UNSUPPORTED_ATTACHMENT","不允許的附件格式");if(!file.buffer.length||file.buffer.length>10*1024*1024)throw new AppError(413,"ATTACHMENT_TOO_LARGE","附件大小不符");return provider.addOnboardingAttachment(id,{attachmentId:crypto.randomUUID(),fileName:text(file.fileName,180),contentType:file.contentType,byteSize:file.buffer.length,sha256:crypto.createHash("sha256").update(file.buffer).digest("hex"),base64:file.buffer.toString("base64")});},
    async submit(id,token){const item=await this.preview(id,token);if(item.completeness.missing.length)throw new AppError(400,"APPLICATION_INCOMPLETE","申請資料尚未完整");return provider.submitOnboarding(id);},
    isPlatformAdmin(session){return Boolean(session&&provider.isPlatformAdmin(session.propertyId,session.username));},list(){return provider.listOnboarding();},get(id){const x=provider.getOnboarding(id);if(!x)throw new AppError(404,"APPLICATION_NOT_FOUND","找不到申請案件");return{...x,completeness:completeness(x)};},review(id,status,note,session){return provider.reviewOnboarding(id,status,text(note,1000),session.propertyId,session.username);},
    approve(id,input,session){const propertyId=text(input.propertyId,48);if(!PROPERTY_ID.test(propertyId))throw new AppError(400,"INVALID_PROPERTY_ID","propertyId 格式錯誤");const adminUsername=text(input.adminUsername,80);if(!adminUsername)throw new AppError(400,"MISSING_ADMIN_USERNAME","請指定後台帳號");const token=crypto.randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+7*86400000).toISOString();try{provider.approveOnboarding(id,propertyId,adminUsername,sessionTokenHash(token),expiresAt,session.propertyId,session.username);}catch(e){if(/already exists/.test(e.message))throw new AppError(409,"PROPERTY_ID_CONFLICT","propertyId 已存在");throw e;}return{propertyId,adminUsername,adminSetupToken:token,guestUrl:`/guest?propertyId=${propertyId}`,adminUrl:"/admin"};},
    async redeemInvitation(token,password){const passwordHash=await hashPassword(password);try{return provider.redeemAdminInvitation(sessionTokenHash(token),passwordHash);}catch{throw new AppError(400,"INVALID_ADMIN_INVITATION","邀請無效或已過期");}}
  };
}
module.exports={createOnboardingService,cleanInput,completeness};
