"use strict";
const crypto=require("node:crypto");
const {AppError}=require("./mvp-service"),{hashPassword,sessionTokenHash}=require("./admin-auth");
const PROPERTY_ID=/^[a-z][a-z0-9_]{2,47}$/;
function text(value,max=500){const v=String(value||"").trim();if(v.length>max)throw new AppError(400,"TEXT_TOO_LONG","輸入內容過長");return v;}
function integer(value,min=0){const n=Number(value);if(!Number.isInteger(n)||n<min)throw new AppError(400,"INVALID_NUMBER","請輸入有效數字");return n;}
function validTime(value){const v=text(value,5);if(!/^(?:[01]\d|2[0-3]):(?:00|30)$/.test(v))throw new AppError(400,"INVALID_TIME","時間必須以 30 分鐘為單位");return v;}
function cleanInput(input={}){
 const rooms=(input.rooms||[]).map((x,i)=>({key:text(x.key||`room_${i+1}`,40),name:text(x.name,80),type:text(x.type,40),capacity:integer(x.capacity,1),mondayThursdayPrice:integer(x.mondayThursdayPrice),fridayPrice:integer(x.fridayPrice),saturdayHolidayPrice:integer(x.saturdayHolidayPrice),sundayPrice:integer(x.sundayPrice),enabled:x.enabled!==false}));
 const keys=new Set(rooms.map(x=>x.key));if(keys.size!==rooms.length)throw new AppError(400,"DUPLICATE_ROOM_KEY","房型識別重複");
 const bundles=(input.bundles||[]).map((x,i)=>{const members=[...new Set((x.memberRoomKeys||[]).map(v=>text(v,40)))];if(!members.length||members.some(k=>!keys.has(k)))throw new AppError(400,"INVALID_BUNDLE_MEMBER","包棟成員房型錯誤");return{key:text(x.key||`bundle_${i+1}`,40),name:text(x.name,80),memberRoomKeys:members,capacity:integer(x.capacity,1),basePrice:integer(x.basePrice),enabled:x.enabled!==false};});
 const knowledge=(input.knowledge||[]).filter(x=>x.key!=="other").map((x,i)=>{const status=["fixed","unavailable","human_handoff","undecided"].includes(x.status)?x.status:"undecided",answer=text(x.answer,1000);if(status==="fixed"&&!answer)throw new AppError(400,"MISSING_KNOWLEDGE_ANSWER",`${text(x.label||x.key,120)}需要填寫內容`);return{key:text(x.key||`faq_${i+1}`,80),label:text(x.label,120),status,answer};});
 return{propertyName:text(input.propertyName,100),contactName:text(input.contactName,80),phone:text(input.phone,40),email:text(input.email,160),address:text(input.address,300),checkInTime:validTime(input.checkInTime),checkOutTime:validTime(input.checkOutTime),line:{hasOfficialAccount:Boolean(input.line&&input.line.hasOfficialAccount),channelId:text(input.line&&input.line.channelId,80),contactLink:text(input.line&&input.line.contactLink,500)},propertyIdSuggestion:text(input.propertyIdSuggestion,48),rooms,bundles,knowledge};
}
const LABELS={propertyName:"民宿正式名稱",contactName:"聯絡人姓名",phone:"聯絡電話",email:"Email",address:"地址",checkInTime:"入住時間",checkOutTime:"退房時間",rooms:"至少一個房型"};
function completeness(app){const required=["propertyName","contactName","phone","email","address","checkInTime","checkOutTime"],missing=required.filter(k=>!app[k]);if(!app.rooms||!app.rooms.length)missing.push("rooms");return{percent:Math.round((required.length+1-missing.length)/(required.length+1)*100),missing,missingLabels:missing.map(x=>LABELS[x]||x),contradictions:[]};}
function createOnboardingService(provider){if(!provider)return null;async function authorized(id,token){if(!token||!provider.verifyOnboardingToken(id,sessionTokenHash(token)))throw new AppError(401,"INVALID_DRAFT_TOKEN","草稿驗證失敗");}return{
 createDraft(){const applicationId=crypto.randomUUID(),draftToken=crypto.randomBytes(32).toString("base64url");provider.createOnboarding(applicationId,sessionTokenHash(draftToken));return{applicationId,draftToken,status:"draft"};},
 async getDraft(id,token){await authorized(id,token);const item=provider.getOnboarding(id);if(!item)throw new AppError(404,"APPLICATION_NOT_FOUND","找不到申請案件");return item;},async saveDraft(id,token,input){await authorized(id,token);return provider.saveOnboarding(id,cleanInput(input));},async preview(id,token){const item=await this.getDraft(id,token);return{...item,completeness:completeness(item)};},
 async submit(id,token){const item=await this.preview(id,token);if(["submitted","resubmitted","approved"].includes(item.status))return item;if(item.completeness.missing.length)throw new AppError(400,"APPLICATION_INCOMPLETE",`尚缺少：${item.completeness.missingLabels.join("、")}`);return provider.submitOnboarding(id);},
 isPlatformAdmin(s){return Boolean(s&&provider.isPlatformAdmin(s.propertyId,s.username));},list(){return provider.listOnboarding();},get(id){const x=provider.getOnboardingForReview(id);if(!x)throw new AppError(404,"APPLICATION_NOT_FOUND","找不到申請案件");return{...x,completeness:completeness(x)};},review(id,status,note,s){return provider.reviewOnboarding(id,status,text(note,1000),s.propertyId,s.username);},
 approve(id,input,s){const propertyId=text(input.propertyId,48);if(!PROPERTY_ID.test(propertyId))throw new AppError(400,"INVALID_PROPERTY_ID","propertyId 格式錯誤");const adminUsername=text(input.adminUsername,80);if(!adminUsername)throw new AppError(400,"MISSING_ADMIN_USERNAME","請指定後台帳號");const token=crypto.randomBytes(32).toString("base64url"),expiresAt=new Date(Date.now()+7*86400000).toISOString();try{provider.approveOnboarding(id,propertyId,adminUsername,sessionTokenHash(token),expiresAt,s.propertyId,s.username);}catch(e){if(/already exists/.test(e.message))throw new AppError(409,"PROPERTY_ID_CONFLICT","propertyId 已存在");throw e;}return{propertyId,adminUsername,adminSetupToken:token,guestUrl:`/guest?propertyId=${propertyId}`,adminUrl:"/admin"};},
 async redeemInvitation(token,password){const passwordHash=await hashPassword(password);try{return provider.redeemAdminInvitation(sessionTokenHash(token),passwordHash);}catch{throw new AppError(400,"INVALID_ADMIN_INVITATION","邀請碼無效或已使用");}}
};}
module.exports={createOnboardingService,cleanInput,completeness};
